### ISSUE TITLE
direct link to internship information page

### ISSUE THREAD

**Issue by GochoMugo** [Khwilo/cs-industrial-attachment#3]
It would be nice to have a **direct link** to the internship/attachment information page. Some of the corporate websites are painful in navigating.

Btw, I like this project :100: :+1:

**Comment by khwilo** [comment]
I'll get to that. Although most of them have a jobs or careers page. I don't know if that would suffice.

**Comment by GochoMugo** [comment]
It is better than nothing. Maybe put it in a separate column like:

| Company name | Location | Jobs page |
| --- | --- | --- |
| [Foo](http://example.org) | Example | [link](http://example.org) |
| [Bar](http://example.org) | Example 2 | - |

Using a dash when there's no link. Sth like it.

**Comment by khwilo** [comment]
I have now added the careers page.

**Comment by GochoMugo** [comment]
:+1: Great!
